<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/HlslPerf.GpuDriven/HlslPerf.GpuDriven.csproj" />
    <None Include="README.md" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../LICENSE.md" Link="LICENSE.md" CopyToPublishDirectory="PreserveNewest" />
    <None Include="../../NOTICE.md" Link="NOTICE.md" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
