<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hlslperf-unified</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HlslPerf.Core/HlslPerf.Core.csproj" />
    <ProjectReference Include="../HlslPerf.D3D12/HlslPerf.D3D12.csproj" />
    <ProjectReference Include="../HlslPerf.Workloads/HlslPerf.Workloads.csproj" />
  </ItemGroup>
</Project>
