<?xml version='1.0' encoding='utf-8'?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <PlatformToolset>v143</PlatformToolset>
    <UseDebugLibraries>false</UseDebugLibraries>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <PropertyGroup>
    <OutDir>D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\scan\</OutDir>
    <IntDir>D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\scan-obj\</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <PrecompiledHeader>NotUsing</PrecompiledHeader>
      <ForcedIncludeFiles>algorithm;array;stdexcept</ForcedIncludeFiles>
      <WarningLevel>Level3</WarningLevel>
      <Optimization>MaxSpeed</Optimization>
      <PreprocessorDefinitions>_CRT_SECURE_NO_WARNINGS;_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS;NDEBUG;HLSLPERF_REPOSITORY="D:/CodexWork/hlsl-scan-inclusive-20260915"</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12;D:\CodexWork\hlsl-scan-inclusive-20260915\benchmarks\external\native;D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\packages\Microsoft.Direct3D.D3D12\build\native\include;D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\packages\Microsoft.Direct3D.DXC\build\native\include;D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\packages\Microsoft.Windows.ImplementationLibrary\include</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalDependencies>dxgi.lib;d3d12.lib;dxcompiler.lib;runtimeobject.lib;windowsapp.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>D:\CodexWork\hlsl-scan-inclusive-20260915\.scratch\native-02\packages\Microsoft.Direct3D.DXC\build\native\lib\x64</AdditionalLibraryDirectories>
      <SubSystem>Console</SubSystem>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\benchmarks\external\native\scan-main.cpp" />
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12\ChainedScanDecoupledLookback.cpp" />
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12\ChainedScanDecoupledLookbackDecoupledFallback.cpp" />
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12\EmulatedDeadlock.cpp" />
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12\ReduceThenScan.cpp" />
    <ClCompile Include="D:\CodexWork\hlsl-scan-inclusive-20260915\third_party\gpu-prefix-sums\GPUPrefixSumsD3D12\Survey.cpp" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>